server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          # Enable service discovery integration
          enabled: true
          lower-case-service-id: true
      routes:
        - id: product-service
          # Use load-balanced service name from Eureka
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products/**
          filters:
            - name: CircuitBreaker
              args:
                name: productService
                fallbackUri: forward:/fallback/product-service
            - RewritePath=/api/v1/(?<segment>.*), /api/v1/$\{segment}
            
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - name: CircuitBreaker
              args:
                name: orderService
                fallbackUri: forward:/fallback/order-service
            - RewritePath=/api/v1/(?<segment>.*), /api/v1/$\{segment}
            
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: userService
                fallbackUri: forward:/fallback/user-service
            - RewritePath=/api/v1/(?<segment>.*), /api/v1/$\{segment}

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,routes,circuitbreakers
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

# Logging
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty: DEBUG

# Resilience4j Configuration
resilience4j.circuitbreaker:
  instances:
    productService: # This name must match the name in the @CircuitBreaker annotation
      register-health-indicator: true
      sliding-window-size: 10
      failure-rate-threshold: 50 # Percentage
      wait-duration-in-open-state: 10s # Time to wait before moving to HALF_OPEN
      permitted-number-of-calls-in-half-open-state: 3

resilience4j.retry:
  instances:
    productService:
      max-attempts: 3
      wait-duration: 100ms