server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10
  client:
    # A eureka server is not a eureka client. It shouldn't register itself.
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    # In a real cluster, you'd turn this on. For a single dev instance, it's simpler to disable.
    enable-self-preservation: false
    wait-time-in-ms-when-sync-empty: 0

logging:
  level:
    root: INFO
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO
